dist: trusty
jobs:
    include:
       - stage: "Static tests"
         name: "Static tests"
         addons:
            sonarcloud:
                organization: "sgt390-github"
                token:
                  secure: "$SONAR_TOKEN"
         script: sonar-scanner
       - stage: deploy
         script: bash scripts/deploy.sh
         deploy:
               provider: lambda
               function_name: "megalexa"
               region: "us-east-1"
               role: "arn:aws:iam::401184049861:role/service-role/basicpermission"
               runtime: "nodejs8.10"
               handler_name: "handler"
               zip: "lambda/"
               on:
                  branch: develop
stages:
  - "Static tests"
  - deploy      
notifications:
  slack: zerosevengroup:awH2p9uSzEPY9plMSyKBtAHF
